### ISSUE TITLE
1.21.2/3/4 Support

### ISSUE THREAD

**Issue by PieKing1215** [PieKing1215/InvMove#68]
1.21.2 refactored some stuff around inputs and the recipe book so it'll require an update to fix (coming soon)
(edit: 1.21.4 refactored inputs even more so that will also need another update)

**Comment by PieKing1215** [comment]
I still need to do some testing to make sure the update doesn't break anything, and there's a few bugs I want to fix before releasing
But if anyone wants to try out dev builds of 0.9 you can access them here (*NOTE: dev builds are not well-tested*)
https://github.com/PieKing1215/InvMove/actions?query=branch%3Av3+is%3Asuccess

Sign into GitHub, click the top one, scroll down to artifacts and click the file to download
Inside the zip there's jars for various Minecraft versions from 1.16.5 to 1.21.4 for Fabric/NeoForge/Forge

(note: if you have InvMoveCompats it will not work with InvMove 0.9 right now, I'll need to update it eventually too)

The main "feature" of the update is that I restructured the entire project again to reduce duplicate code between versions & simplify the build system, with the goal of reducing the effort needed to update & support many versions.

But there's also a few features/fixes:
- Better compatibility with mods that add keybinds related to movement
(crawling, auto walk/run, third person mods, ItemSwapper+MouseWheelie)
- Movement config now has a section that lets you configure what keys are force updated by InvMove while in inventories
(only the vanilla movement keys are enabled by default to keep it safer for mod compatibility)
(before this it used to force update ALL keys which caused issues with some mods)
- Option to disable movement while the recipe book is open (false by default)

If you notice any issues please let me know, especially issues that weren't present in InvMove 0.8.x

**Comment by znopp** [comment]
So far no issues, been using the 817b15f commit!

**Comment by aaronjamt** [comment]
I also haven't noticed any issues, although I haven't thoroughly tested or tried to break it. Normal gameplay seems to work fine.

**Comment by PINPAL** [comment]
Generally no issues for me, but the in-game config menu via ModMenu does not work (just doesn't open). 
- Fabric
- Minecraft 1.21.4
- Tested on commit b8ea72a

**Comment by PieKing1215** [comment]
>  in-game config menu via ModMenu does not work (just doesn't open).

@PINPAL is this with a modpack & does it log an error in the console?
(It works for me with just InvMove b8ea72a, Cloth Config 17.0.144, Mod Menu 13.0.0, and Fabric API 0.114.3+1.21.4 so could be some conflict with another mod)

**Comment by PINPAL** [comment]
> > in-game config menu via ModMenu does not work (just doesn't open).
> 
> @PINPAL is this with a modpack & does it log an error in the console? (It works for me with just InvMove [b8ea72a](https://github.com/PieKing1215/InvMove/commit/b8ea72ab77877bfdeef8923c41bb08ed3b3d1abe), Cloth Config 17.0.144, Mod Menu 13.0.0, and Fabric API 0.114.3+1.21.4 so could be some conflict with another mod)

```log
[20:48:16] [Render thread/ERROR]: Error from mod 'invmove'
java.lang.NullPointerException: Cannot read field "value" because "anotherInteger" is null
	at java.base/java.lang.Integer.compareTo(Integer.java:1469) ~[?:?]
	at knot/net.minecraft.class_304.method_1430(class_304.java:143) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_304.compareTo(class_304.java:15) ~[client-intermediary.jar:?]
	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:52) ~[?:?]
	at java.base/java.util.Comparators$NaturalOrderComparator.compare(Comparators.java:47) ~[?:?]
	at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:355) ~[?:?]
	at java.base/java.util.TimSort.sort(TimSort.java:234) ~[?:?]
	at java.base/java.util.Arrays.sort(Arrays.java:1308) ~[?:?]
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:353) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at knot/me.pieking1215.invmove.InvMoveConfig.setupCloth(InvMoveConfig.java:102) ~[InvMove-b8ea72a+1.21.4-Fabric.jar:?]
	at knot/com.terraformersmc.modmenu.ModMenu.getConfigScreen(ModMenu.java:70) ~[modmenu-13.0.0.jar:?]
	at knot/com.terraformersmc.modmenu.gui.ModsScreen.safelyOpenConfigScreen(ModsScreen.java:645) ~[modmenu-13.0.0.jar:?]
	at knot/com.terraformersmc.modmenu.gui.ModsScreen.lambda$init$4(ModsScreen.java:188) ~[modmenu-13.0.0.jar:?]
	at knot/net.minecraft.class_4185.method_25306(class_4185.java:96) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4264.method_25348(class_4264.java:43) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_339.method_25402(class_339.java:141) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4069.method_25402(class_4069.java:43) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.mixinextras$bridge$method_25402$55(class_312.java) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.wrapOperation$cfc000$fabric-screen-api-v1$invokeMouseClickedEvents(class_312.java:2545) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_1601(class_312.java:114) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22686(class_312.java:215) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.execute(class_1255.java:110) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_312.method_22684(class_312.java:215) ~[client-intermediary.jar:?]
	at knot/org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.3.jar:?]
	at knot/com.moulberry.axiom.editor.CustomImGuiImplGlfw.mouseButtonCallback(CustomImGuiImplGlfw.java:221) ~[Axiom-4.4.0-for-MC1.21.4.jar:?]
	at knot/org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) [lwjgl-glfw-3.3.3.jar:?]
	at knot/org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.3.jar:?]
	at knot/org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3438) [lwjgl-glfw-3.3.3.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:149) [client-intermediary.jar:?]
	at knot/com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:170) [client-intermediary.jar:?]
	at knot/net.minecraft.class_1041.method_15998(class_1041.java:318) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1361) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:922) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:267) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
```

I tried deleting my config file as I thought perhaps it was related but that didn't do anything other than reset my settings (obviously).

Edit: Upon further investigation by painstakingly turning off each of my mods one at a time, I figured out when I have [ClickThrough Mod](https://modrinth.com/mod/clickthrough+) installed, the open config button doesn't work ONLY for InvMove (the button for every other mod works completely fine?). So I guess it's a compatibility thing just extremely odd behaviour.

**Comment by PieKing1215** [comment]
Looks like a bug in vanilla's key sorting function
If you get a chance once this run finishes can you see if that fixes it: https://github.com/PieKing1215/InvMove/actions/runs/12797755023

**Comment by PINPAL** [comment]
> Looks like a bug in vanilla's key sorting function If you get a chance once this run finishes can you see if that fixes it: https://github.com/PieKing1215/InvMove/actions/runs/12797755023

Works perfectly. Thanks for your support <3

**Comment by iriscal** [comment]
Is this ever going to happen?

**Comment by PieKing1215** [comment]
> Is this ever going to happen?

Yeah :)
I did some light testing in a few modpacks and it seemed fine, looking to release this week unless something comes up

Last weekend I also took some time to port InvMoveCompats to the new build setup, so that'll also release with REI/JEI/EMI support alongside the base mod update

Dev builds for InvMoveCompats here if anyone wants to try (lmk how it goes)
https://github.com/PieKing1215/InvMoveCompats/actions/workflows/gradle-build-jars.yml?query=is%3Asuccess
*(sign into GitHub, click the top run, scroll down to artifacts and click the file to download. Inside the zip there's jars for various Minecraft versions)*

**Comment by PieKing1215** [comment]
[v0.9.0](https://github.com/PieKing1215/InvMove/releases/tag/v0.9.0) is out now ([also on Modrinth](https://modrinth.com/mod/invmove/versions))!
If anyone has any problems please open an issue :)
